### PR TITLE
Implemented html code counting

### PR DESCRIPTION
**Pull request by lukasoppermann**
Hey @jeroenvisser101 I fixed it so that `<code></code>` is also estimated, like markdown code blocks.

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
@lukasoppermann – Thanks! We might want to move the `$story` in some text files to make the tests cleaner and easier to read.

**Comment by lukasoppermann** [comment]
@jeroenvisser101 we could, but I think this should happen in a separate PR and for all tests. 
Probably best though, to have all texts in one file to include, not separate files for very text, which would be a messy lot of files.

Also something seems to be off with TRAVIS:

```
Checked all files in 0.583 seconds, 8.250 MB memory used
Script echo '\033[1;33m
Running: php codesniffer...\033[0m'; vendor/bin/phpcs --standard=PSR2 src/Bookworm/Bookworm.php && echo '\033[1;33mRunning: phpunit...\033[0m'; phpunit && vendor/bin/php-cs-fixer fix --diff -v --dry-run src handling the test event returned with an error

  [RuntimeException]                                                           
  Error Output: You are running php-cs-fixer with xdebug enabled. This has a   
  major impact on runtime performance. 
```

**Comment by jeroenvisser101** [comment]
https://travis-ci.org/worddrop/bookworm/jobs/114889671#L403-L404 -> if you could fix those, I think travis should be passing

**Comment by jeroenvisser101** [comment]
@lukasoppermann – I've added you as a contributor, so if the required status checks pass, you can merge this yourself :+1:

**Comment by jeroenvisser101** [comment]
:+1:

**Comment by lukasoppermann** [comment]
Thanks.  :+1:

**Pull request merged**
