### PR TITLE
Add markdown code estimate

### PR DESCRIPTION
**Pull request by lukasoppermann**
This PR adds an estimate for code blocks in markdown. They are calculated using the `$codewordsPerMinute` variable which is the same as words per minute by default.

Attributes on tags are calculated as individual words, but the content of attributes is ignored. This solves issues like svgs having extreme amounts of "words" in the `d` attribute, which nobody will read in any case.

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
@lukasoppermann I think this PR adds to much logic to that one class. If we want it to do multiple passes (and allow it to add seconds per pass), we should do this in different classes I think. That would also allow users to create such a pass themselves, for a specific case. What do you think?

**Comment by lukasoppermann** [comment]
I do like the idea, although I do not have a clear idea in how you mean to
implement it. But if you merge this PR we would have all functions we need
in the code (some extension for html code blocks is still needed) and you
could refactor it with your idea. This way you immediately know how well it
works with different types of estimations.

**Comment by lukasoppermann** [comment]
Hey @jeroenvisser101 can you pull this, so we can start on the refactoring?

**Comment by jeroenvisser101** [comment]
@lukasoppermann surely, I've not had a lot of time lately, but possibly after this friday!

**Comment by lukasoppermann** [comment]
Awesome, thanks. I will see if I can get a PR for some refactoring soon. Thanks. :+1:

**Pull request merged**
