### PR TITLE
Refactor to use provided strings instead of translation config

### PR DESCRIPTION
**Pull request by lukasoppermann**
I probably missed some PSR-2 things, please let me know. This PR changes the following:
- remove translations entirely 
- change config to array & add option to set time for images
- add possible pluralization

Defaults to _minute_ and _minutes_. You have to add the leading whitespace to the units, this is to make it possible to add units without whitespace as well. Like `4m`.

``` php
# default (plural)
$readingTime = Bookworm::estimate($story); // 1 minute or 8 minutes
# singular
$readingTime = Bookworm::estimate($story, 'm'); // 1m or 8m
# plural
$readingTime = Bookworm::estimate($story, [' minute',' minutes']); // 1 minute or 8 minutes
# none
$readingTime = Bookworm::estimate($story, false); // 1 or 8
```

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey, no idea why it cries, but its not PSR2 you are testing all standards. Couldn't we change it to use php-cs, php-cs-fixer is really annoying, as they f***ed up the reporting and you can't get line numbers, so it is basically uselss. And there is not really movement on adding it: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1370 :(

**Comment by lukasoppermann** [comment]
Also, once this is merged, could you tag a new version? Otherwise I can't get it trough composer.

**Comment by lukasoppermann** [comment]
Hey @jeroenvisser101 will you be able to merge it like this?

**Comment by jeroenvisser101** [comment]
@lukasoppermann Hey, I'm sorry to answer late, busy week.

CI seems to fail because of cs-fixer. I think it's related to the docblocks. Could you run it locally and see what the auto-fix does?

Also, once this will be merged I'll tag it :)

**Comment by lukasoppermann** [comment]
Okay, it now fails on PHP 5.3 due to `[]`array syntax. I would suggest to kill of PHP 5.3 as it is not supported anymore and will die off, and keep the nice array syntax.

**Comment by jeroenvisser101** [comment]
@lukasoppermann I want to do that, but not in this PR. I'd like to keep them as small as possible :)

**Comment by lukasoppermann** [comment]
So are you saying I should fix it, and we change it back later on?

**Comment by jeroenvisser101** [comment]
Yes :)

**Comment by lukasoppermann** [comment]
Finally it passed, please if you want to keep using php-cs-fixer, do it using a local install n the vendor folder, so that when somebody tests via composer it runs the same exactly same tests as on the server. For e.g. the `all` level you use on travis, does somehow not work if I composer require `php-cs-fixer` locally.

**Comment by lukasoppermann** [comment]
Hey @jeroenvisser101 could you merge this? I am working on the code block estimate and I need this to be pulled so I don't have to write it twice. Thanks.

**Comment by lukasoppermann** [comment]
Awesome, thanks. :+1:

**Comment by jeroenvisser101** [comment]
@lukasoppermann I also added a tag (0.2.0). Since 5.3 is now deprecated I think the usage of `array()` can now be deprecated. I'll work on that in #9.

**Comment by lukasoppermann** [comment]
Nice!

**Pull request merged**
